'use strict';
const REPO='yuyami86/gym-recipe-test', BRANCH='main', POSTS='src/posts', UPLOADS='src/assets/uploads', KEY='recipeGithubToken';
const $=s=>document.querySelector(s), form=$('#editorForm');
let token=sessionStorage.getItem(KEY)||'', posts=[], current=null, pendingImage=null;
const fields=()=>Object.fromEntries(new FormData(form).entries());
const enc=s=>s.split('/').map(encodeURIComponent).join('/');
const decode64=s=>decodeURIComponent(escape(atob(s.replace(/\n/g,''))));
const encode64=s=>btoa(unescape(encodeURIComponent(s)));
function message(el,text,error=false){el.textContent=text;el.classList.toggle('error',error)}
async function api(path,options={}){const r=await fetch('https://api.github.com/repos/'+REPO+path,{...options,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})}});if(!r.ok){let detail='';try{detail=(await r.json()).message}catch{}throw new Error(r.status===401?'キーが正しくないか、有効期限が切れています。':r.status===403?'このキーに必要な権限がありません。ContentsをRead and writeにしてください。':r.status===404?'リポジトリが選択されていないか、ファイルが見つかりません。':detail||`GitHubエラー (${r.status})`)}return r.status===204?null:r.json()}
async function connect(){token=$('#tokenInput').value.trim();if(!token)return message($('#loginMessage'),'キーを入力してください。',true);setBusy($('#loginButton'),true,'確認中…');try{const repo=await api('');if(!repo.permissions?.push)throw new Error('このキーにはリポジトリへの書き込み権限がありません。');sessionStorage.setItem(KEY,token);showManager(repo.full_name);await loadPosts()}catch(e){token='';sessionStorage.removeItem(KEY);message($('#loginMessage'),e.message,true)}finally{setBusy($('#loginButton'),false,'接続する')}}
function showManager(name=REPO){$('#loginView').hidden=true;$('#managerView').hidden=false;$('#logoutButton').hidden=false;$('#connectionLabel').textContent=name+' に接続中'}
function logout(){sessionStorage.removeItem(KEY);token='';location.reload()}
function setBusy(button,on,label){button.disabled=on;button.textContent=label}
async function loadPosts(){const list=$('#postList');list.innerHTML='<div class="loading">記事を読み込み中…</div>';try{const files=await api('/contents/'+enc(POSTS)+'?ref='+BRANCH);const jsonFiles=files.filter(f=>f.type==='file'&&f.name.endsWith('.json'));posts=await Promise.all(jsonFiles.map(async f=>{const data=await api('/contents/'+enc(f.path)+'?ref='+BRANCH);return {...JSON.parse(decode64(data.content)),_name:f.name,_path:f.path,_sha:data.sha}}));posts.sort((a,b)=>String(b.date).localeCompare(String(a.date)));renderPosts()}catch(e){list.innerHTML='<p class="empty-list">'+escapeHtml(e.message)+'</p>'}}
function renderPosts(){const q=$('#searchInput').value.trim().toLowerCase(), filtered=posts.filter(p=>(p.title+' '+p.category+' '+p.date).toLowerCase().includes(q));$('#postList').innerHTML=filtered.length?filtered.map(p=>`<button class="post-item${current?._path===p._path?' active':''}" type="button" data-path="${escapeHtml(p._path)}"><strong>${escapeHtml(p.title)}</strong><span>${escapeHtml(p.date)} / ${escapeHtml(p.category)}</span></button>`).join(''):'<p class="empty-list">該当する記事はありません。</p>';document.querySelectorAll('.post-item').forEach(b=>b.onclick=()=>editPost(posts.find(p=>p._path===b.dataset.path)))}
function newPost(){current=null;pendingImage=null;form.reset();form.elements.date.value=new Date().toISOString().slice(0,10);form.elements.category.value='TRAINING';form.elements.slug.disabled=false;$('#imagePreview').hidden=true;$('#deleteButton').hidden=true;$('#editorMode').textContent='NEW POST';$('#editorHeading').textContent='新しい記事';openEditor();renderPosts()}
function editPost(post){current=post;pendingImage=null;for(const name of ['title','date','category','coverLabel','excerpt','image','body'])form.elements[name].value=post[name]||'';form.elements.slug.value=post._name.replace(/\.json$/,'').replace(/^\d{4}-\d{2}-\d{2}-/,'');form.elements.slug.disabled=true;previewExisting(post.image);$('#deleteButton').hidden=false;$('#editorMode').textContent='EDIT POST';$('#editorHeading').textContent='記事を編集';openEditor();renderPosts()}
function openEditor(){$('#emptyEditor').hidden=true;form.hidden=false;message($('#editorMessage'),'');window.scrollTo({top:0,behavior:'smooth'})}
function previewExisting(path){const img=$('#imagePreview');if(path){img.src='/gym-recipe-test'+path;img.hidden=false}else{img.hidden=true;img.removeAttribute('src')}}
function safeName(name){const dot=name.lastIndexOf('.'), ext=dot>=0?name.slice(dot).toLowerCase():'';return (dot>=0?name.slice(0,dot):name).normalize('NFKC').replace(/[^a-zA-Z0-9ぁ-んァ-ヶ一-龠_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)+'-'+Date.now()+ext}
function readImage(file){if(!file){pendingImage=null;return}if(file.size>5*1024*1024){$('#imageFile').value='';return message($('#editorMessage'),'画像は5MB以下にしてください。',true)}const reader=new FileReader();reader.onload=()=>{pendingImage={name:safeName(file.name),base64:String(reader.result).split(',')[1]};const img=$('#imagePreview');img.src=reader.result;img.hidden=false};reader.readAsDataURL(file)}
async function putFile(path,content,sha,messageText){return api('/contents/'+enc(path),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:messageText,content,branch:BRANCH,...(sha?{sha}:{})})})}
async function savePost(e){e.preventDefault();if(!form.reportValidity())return;const save=$('#saveButton'),data=fields();setBusy(save,true,'保存中…');message($('#editorMessage'),'GitHubへ保存しています。ページを閉じないでください。');try{if(pendingImage){const imagePath=UPLOADS+'/'+pendingImage.name;await putFile(imagePath,pendingImage.base64,null,'Add journal image: '+pendingImage.name);data.image='/assets/uploads/'+pendingImage.name}else data.image=data.image.trim();delete data.slug;const filename=current?current._name:`${data.date}-${form.elements.slug.value.trim()}.json`;const path=POSTS+'/'+filename;await putFile(path,encode64(JSON.stringify(data,null,2)+'\n'),current?current._sha:null,(current?'Update':'Add')+' journal post: '+data.title);message($('#editorMessage'),'保存しました。公開ページは通常1〜2分で自動更新されます。');await loadPosts();editPost(posts.find(p=>p._path===path))}catch(err){message($('#editorMessage'),err.message,true)}finally{setBusy(save,false,'GitHubへ保存')}}
async function deletePost(){if(!current||!confirm(`「${current.title}」を削除しますか？この操作はGitHubの履歴から戻せます。`))return;setBusy($('#deleteButton'),true,'削除中…');try{await api('/contents/'+enc(current._path),{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Delete journal post: '+current.title,sha:current._sha,branch:BRANCH})});current=null;form.hidden=true;$('#emptyEditor').hidden=false;await loadPosts()}catch(e){message($('#editorMessage'),e.message,true)}finally{setBusy($('#deleteButton'),false,'削除') }}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#loginButton').onclick=connect;$('#tokenInput').onkeydown=e=>{if(e.key==='Enter')connect()};$('#showToken').onchange=e=>$('#tokenInput').type=e.target.checked?'text':'password';$('#logoutButton').onclick=logout;$('#newButton').onclick=newPost;$('#searchInput').oninput=renderPosts;$('#imageFile').onchange=e=>readImage(e.target.files[0]);form.onsubmit=savePost;$('#deleteButton').onclick=deletePost;
if(token){showManager();loadPosts()}
